### ISSUE TITLE
Create a release for use in a Zed extension

### ISSUE THREAD

**Issue by ewen-lbh** [mrnossiom/wakatime-lsp#2]
Hi!! I wanna add Wakatime support to [Zed](https://zed.dev), and basically had [exactly the same idea](https://github.com/ewen-lbh/wakalsp) before realizing that someone else did it before me haha

But to download the LSP server in the extension, I need to point it to a tar.gz, with support for `apple-darwin`, `unknown-linux-gnu` and `pc-windows-msvc`, as well as archs x86, x86_64 and aarch64. It should be doable since you wrote this with ~~the best language ever~~ Rust :)

I understand that you don't want to have it on crates.io yet, but giving out a prebuilt binary would make things a lot more easy :)

**Comment by rodneyosodo** [comment]
It is not a must we publish to crates we can ship with something like https://opensource.axo.dev/cargo-dist/. Here is an example of how I did it https://github.com/0x6flab/sym-calc/tree/main

**Comment by mrnossiom** [comment]
Took a bit longer than expected because I had an outdated version of cargo-dist, but here you have a release with prebuilt binaries: https://github.com/mrnossiom/wakatime-lsp/releases/tag/v0.1.0

**Comment by alanhamlett** [comment]
@mrnossiom what do u think about making this an official wakatime-cli-lsp repo that's used by any plugin needing a WakaTime wrapper via LSP?

**Comment by alanhamlett** [comment]
Update to my comment: We're going to use [zed-wakatime](https://github.com/wakatime/zed-wakatime) as the official WakaTime plugin for Zed. It bundles the lsp server instead of downloading from GitHub on install. I'm not sure which is better, but probably bundling the lsp server has less ways it could fail because there's no network connection necessary?

I still like the idea of re-using a common wakatime-lsp, maybe using [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

**Comment by mrnossiom** [comment]
That should work fine. Do I need to do something special?

**Comment by mrnossiom** [comment]
EDIT: sorry, I read the question wrong 😅

For the Zed use-case, bundling the language server seems like the right thing to do. To get to a common language server impl in a different place, using the crates.io registry would be easier. I can make a quick pull to change this to a library.

I thought about rewriting the ls ditching `tower-lsp` for the simpler [lsp-server](https://docs.rs/lsp-server/latest/lsp_server) (sync, so no need for a runtime like tokio) to get a lower memory footprint.

Another solution (I might have already mentioned it) is to include the ls in the `wakatime-cli`.

Last, you were talking about making the common ls part of the `wakatime` org.

PRs for change to lib, rewrite with lsp are coming later today
